- name: setup Backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable node js
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Creating Expense user
    ansible.builtin.user:
      name: expense

  - name: Creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading Application code to server /tmp directory
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip 

  - name: unzip package to /app
    ansible.builtin.unarchive:
      src: /tmp/backend.zip 
      dest: /app
      remote_src: yes
  
